# Generated by Django 5.1.2 on 2024-10-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=264)),
                ("last_name", models.CharField(max_length=264)),
                ("email", models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
